name: Staging Deployment

on:
  push:
    branches: [ "staging" ]

permissions:
  contents: read

jobs:
  build-and-deploy:
    name: Build And Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.1'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Up Environment Variables
      run: |
        echo "APP_ENV=prod" >> $GITHUB_ENV
        echo "APP_DEBUG=1" >> $GITHUB_ENV
        echo "DATABASE_URL=${{ secrets.STAGING_DATABASE_URL }}" >> $GITHUB_ENV
        echo "MESSENGER_TRANSPORT_DSN=${{ secrets.MESSENGER_TRANSPORT_DSN }}" >> $GITHUB_ENV
        echo "MAILER_DSN=null://null" >> $GITHUB_ENV
        echo "APP_SECRET=${{ secrets.APP_STAGING_SECRET }}" >> $GITHUB_ENV
        echo "HOST='spur1.media'" >> $GITHUB_ENV
        echo "FILE_STORAGE_PATH='public/uploads'" >> $GITHUB_ENV
        echo "CORS_ALLOW_ORIGIN='^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'" >> $GITHUB_ENV

    - name: Dump .env
      run: |
        rm -f .env
        echo "APP_ENV=prod" >> .env
        echo "APP_DEBUG=1" >> .env
        echo "DATABASE_URL='${{ secrets.STAGING_DATABASE_URL }}'" >> .env
        echo "MESSENGER_TRANSPORT_DSN=${{ secrets.MESSENGER_TRANSPORT_DSN }}" >> .env
        echo "MAILER_DSN=null://null" >> .env
        echo "APP_SECRET=${{ secrets.APP_STAGING_SECRET }}" >> .env
        echo "HOST='spur1.media'" >> .env
        echo "FILE_STORAGE_PATH='public/uploads'" >> .env
        echo "CORS_ALLOW_ORIGIN='^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'" >> .env

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Composer
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-dev --optimize-autoloader

    - name: Generate Keys
      run: APP_RUNTIME_ENV=prod php bin/console secrets:generate-keys

    - name: Dump Environment Vars To Production
      run: |
        composer dump-env prod

    # TODO: Manually at the moment
    #- name: Database Migrations
    #  run: php bin/console doctrine:migrations:migrate --no-interaction --all-or-nothing

    - name: Clear Cache, Install Assets
      run: |
        php bin/console cache:clear --no-warmup
        php bin/console assets:install

    - name: Use Node.js 18.16.1
      uses: actions/setup-node@v3
      with:
        node-version: 18.16.1

    - name: Build Encore/NPM
      run: |
        npm cache clean --force
        npm install --force
        npm run build

    - name: ðŸ“‚ Deploy Main & src Files # Deploys /src /bin /config /sync-state /templates /translations and ./ 
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
          timeout: 60000
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./
          protocol: ftps
          server-dir: ${{ secrets.STAGING_BASE_PATH }}/
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dry-run: false
          state-name: sync-state/.main.json
          exclude: |
            **/.git*/**
            **/.git*
            **/.git/**
            **/.github/**
            **/assets/**
            **/migrations/**
            **/node_modules/**
            **/public/**
            **/tests/**
            **/var/**
            **/vendor/**
            **/.env.local
            **/.env.test
            **/.git*
            **/compose.override.yaml
            **/compose.yaml
            **/install.bat
            **/package-lock.json
            **/package.json
            **/phpunit.xml.dist
            **/todo.md
            **/update.bat
            **/webpack.config.js
 
    - name: ðŸ“‚ Deploy Public Assets # Deploys /public
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
          timeout: 60000
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./
          protocol: ftps
          server-dir: ${{ secrets.STAGING_BASE_PATH }}/
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dry-run: false
          state-name: sync-state/.assets.json
          exclude: |
            **/.git*/**
            **/.git*
            **/.git/**
            **/.github/**
            **/assets/**
            **/migrations/**
            **/node_modules/**
            **/sync-state/**
            **/tests/**
            **/var/**
            **/config/**
            **/vendor/**
            **/src/**
            **/bin/**
            **/templates/**
            **/translations/**
            **/.env.local
            **/.env.test
            **/.git*
            **/compose.override.yaml
            **/compose.yaml
            **/install.bat
            **/package-lock.json
            **/package.json
            **/phpunit.xml.dist
            **/todo.md
            **/update.bat
            **/webpack.config.js
            **/.env
            **/.env.local.php
            **/composer.json
            **/composer.lock
            **/symfony.lock
            **/index.php

    - name: ðŸ“‚ Deploy Vendor # Deploys /vendor
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
          timeout: 60000
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./
          protocol: ftps
          server-dir: ${{ secrets.STAGING_BASE_PATH }}/
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dry-run: false
          state-name: sync-state/.vendor.json
          exclude: |
            **/.git*/**
            **/.git*
            **/.git/**
            **/.github/**
            **/assets/**
            **/migrations/**
            **/node_modules/**
            **/config/**
            **/public/**
            **/sync-state/**
            **/templates/**
            **/translations/**
            **/tests/**
            **/var/**
            **/src/**
            **/bin/**
            **/.env.local
            **/.env.test
            **/.git*
            **/compose.override.yaml
            **/compose.yaml
            **/install.bat
            **/package-lock.json
            **/package.json
            **/phpunit.xml.dist
            **/todo.md
            **/update.bat
            **/webpack.config.js
            **/.env
            **/.env.local.php
            **/composer.json
            **/composer.lock
            **/symfony.lock

    - name: Create Empty Directory
      run: mkdir .empty

    - name: ðŸ“‚ Clear Cache # Clears Cache
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
          timeout: 60000
          server: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: .empty/
          protocol: ftps
          server-dir: ${{ secrets.STAGING_BASE_PATH }}/var/cache/
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dangerous-clean-slate	: true
          dry-run: false